### ISSUE TITLE
Logo not being loaded. 

### ISSUE THREAD

**Issue by BIIJESH** [b0sc/b0sc.github.io#1]
The logo in the website are not being loaded while going from the pages back and fourth.

**Comment by devsdenepal** [comment]
Hi @axyut sir! I want to work on this issue, please assign it to me.

**Comment by devsdenepal** [comment]
Let's close this issue?

**Comment by axyut** [comment]
yeah, forgot to close it, you should have put `closes #xxx` in the PR when opening it.

**Comment by BIIJESH** [comment]
![image](https://github.com/user-attachments/assets/a6cce1c6-82aa-4150-828d-082a18bf6b61)
This was the issues about the logo . So reopening it again.

**Comment by axyut** [comment]
@devsdenepal please review and fix it

**Comment by devsdenepal** [comment]
@BIIJESH  I can't find the bug, please state steps to reproduce this bug.

**Comment by BIIJESH** [comment]
Just keep going back and forth on the website, and you should be able to reproduce it @devsdenepal
