### ISSUE TITLE
Wrong input type causing submission error

### ISSUE THREAD

**Issue by devsdenepal** [b0sc/b0sc.github.io#10]
**Problem**: The input type of _Name_ input in the bottom form (.space-y-8 .md:w-full) values to `email` which is preventing users to submit their names as normal text.
![image](https://github.com/user-attachments/assets/875041a8-f0c6-41aa-b58e-7646ca758ec1)

**Comment by axyut** [comment]
name and email might have been interchanged. issue #5 will fix this when done so a seperate issue is not required.
