### ISSUE TITLE
Change FAQ CSS to contain two columns in a row.

### ISSUE THREAD

**Issue by axyut** [b0sc/b0sc.github.io#14]
- [X] PR for this issue must follow the PR template
- [X] This is a bug
- [ ] This is a feature request

## What happend?
The FAQs are taking too much space, reduce(size, text-size, height) them to contain to columns in a row. Leave as it is for mobile devices, that is, one faq in one row, better to reduce the height though.
## What should have happened?
![image](https://github.com/user-attachments/assets/4cac06c8-7d2c-424a-af31-c6c2670b601c)

**Comment by Muhammadahmedanis** [comment]
Assign ma this issue so I can fix it

**Comment by Muhammadahmedanis** [comment]
kindly assign me again by mistake i remove assigning

**Comment by raijin-asr** [comment]
Can you assign me this issue since i am new to Open Source and have fixed this issue? 
My change looks as follows: 

![FAQ](https://github.com/user-attachments/assets/0dc4f1a8-fd7d-4fef-977c-75f8da739105)

If its ok, and i am assigned this issue. i will proceed to create PR. Regards.

**Comment by axyut** [comment]
looks good, also you don't need to be assigned to open PR, if you fixed the issue before anyone just one the pr mentioning, `closes #xxxx` and other details as per pr template.
Its good practice to ask to get assigned before starting the work though so you should have asked to assign you before starting to fix, because if someone else was already working on it and opened PR just before you, your work could have been to waste.

enough lecture, you can open the pr.

**Comment by axyut** [comment]
when closed, the size of the each box should be the same doesn't matter the text's length, i think you fix by decreasing the font size or adding ellipses search for css ellipses or overflow or sth.

**Comment by raijin-asr** [comment]
ok thanks for the suggestion. I will fix the size of box and verify it to you before opening PR.

**Comment by raijin-asr** [comment]
Is this ok?

![fixed box size FAQ](https://github.com/user-attachments/assets/3505c408-129f-481a-a3ec-7d9989699df1)
