### ISSUE TITLE
EventsCard CSS

### ISSUE THREAD

**Issue by axyut** [b0sc/b0sc.github.io#24]
- [X] PR for this issue must follow the PR template
- [ ] This is a bug
- [x] This is a feature request

## For Feature request 
- Explain the working of new feature.
when any of the events from `/blogs` is opened by clicking read more, EventsCard file's data is rendered, write eye catching css and align contents. 
- How will implementing this help this repo?
by making the events blog more readible
- Relevant examples and resources
search on your own, its simple html css issue

**Comment by aayushtmG** [comment]
![Screenshot 2024-11-09 at 15-16-20 BOSC](https://github.com/user-attachments/assets/573a7e23-22d7-48e3-9cc3-ed19261da9d5)
will this styling be appropriate for viewing the blog, if so please let me know. 
Also, why is there so much space above -> all articles link ?

**Comment by axyut** [comment]
> Also, why is there so much space above -> all articles link ?

khai, do make it less if you want, it will be better

> will this styling be appropriate for viewing the blog, if so please let me know.

- [ ] right box style idea is good tesma date ko issue dekhya xa
- [ ] tyo box ni a little bit bigger to have a bigger cover photo inside the box, tya `name_1` pardena baru, cover photo ko size box ko full width hola better hola
- [ ] tyo box vitra mentors ani partners haru only write if there are any, check home page ko Upcoming event for reference
- [ ] tyo box ma entry fee, certs ani prizes ni herni bittikai bujini hos tesari list garna vanda, check home page upcoming event for reference (title ko side ma green box ma huda thyakka chinyaxa)
- [ ] links haru also render if there is link ani use appropriate icons social media, registration, replace blog link with share button ani put blog link there
- [ ] time chai 00:00 AM vaye use alternate time from `stats.time`
- [ ] move pics to description section and bring description section below
- [ ] only render maximum of 4 pics, and based on numbers of pics, 
  - if 4 pics 
![image](https://github.com/user-attachments/assets/56c296f7-6ce9-4558-adb2-213913258d0f)
  - if 3 pics 
![image](https://github.com/user-attachments/assets/dc96118e-94fb-4c3c-bcc3-af1d571ce7a3)
  - if 2 pics 
![image](https://github.com/user-attachments/assets/b9ad12f2-46d3-41fc-90dc-836ced6dc063)
  - if 1 pic, full pic
  - if 0 pic, move desc section up (i think it will happen automatically)

**Comment by axyut** [comment]
@aayushtmG are you actively doing this or are you confident in doing this? will need this done very soon so i'll do this if you've left this issue.

**Comment by aayushtmG** [comment]
Sorry, i wanted to do it, but i have been quite busy. You can go for it.

**Comment by axyut** [comment]
sure thanks for replying so quick. you can do other issues whenever you're free.
