### ISSUE TITLE
Feat : Improve Button Hover Effects for Enhanced User Experience

### ISSUE THREAD

**Issue by rohitmore07** [b0sc/b0sc.github.io#28]
- [x] This is a feature request

The current hover effect on buttons throughout the website could be updated to create a more engaging and responsive feel for users. Enhance the button hover effects by adding smooth transitions, subtle color adjustments, and shadow/scale effects to improve usability and interactivity.

**Benefits :**

- Improved User Experience : Users will receive clear visual feedback on interactive elements, which enhances the overall UX.
- Consistency : Creating uniform button styles across the website ensures users have a cohesive experience, making the site look polished and professionally designed.
- Increased Interactivity : Buttons that respond to user actions feel more dynamic and accessible, which can encourage engagement and ease navigation.

**Comment by axyut** [comment]
sure. not that much of a issue, but we can keep it open only if you want to be assigned to fix it.

**Comment by BIIJESH** [comment]
Hey, @rohitmore07. If you want to make the changes, make sure to raise the pr.

**Comment by rohitmore07** [comment]
> sure. not that much of a issue, but we can keep it open only if you want to be assigned to fix it.

As per UX guidelines, I'm suggesting this improvement since the current design could be more visually appealing and user-friendly. It may not seem critical, but refining this aspect would enhance the overall look and feel.

**Comment by rohitmore07** [comment]
> Hey, @rohitmore07. If you want to make the changes, make sure to raise the pr.

Sure.

**Comment by BIIJESH** [comment]
Hey @rohitmore07 are you working on the issue or not?  If not we can close the issue .

**Comment by rohitmore07** [comment]
@BIIJESH Yes, I'm currently working on the issue and will be raising a PR by tomorrow.
