### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by axyut** [b0sc/b0sc.github.io#5]
A section for collecting emails such that whenever any new BOSC event is scheduled, the subscribers are notified automatically, will serve as a great tool to advertise and increase BOSC's reach.

**Comment by devsdenepal** [comment]
@axyut Do you want a subscription form or a notification section?

**Comment by axyut** [comment]
I've not thought of a complete implementation but the general idea is it will be in the Contact section in bottom of the Home Page. 
![image](https://github.com/user-attachments/assets/294cecaa-02b8-4d49-a4d5-1174afb6acb4)
UI part
- `Subscribe to Newsletter` button will be placed right side of the `Send Message` 
- Make Message input box not required by placing `*` on other two input fields
- Remove both  `Say Hi` and `Membership` radio button


Logic part
- When `Subscribe to Newsletter` is pressed, email is collected forward to a `newsletter service`
- Find the feasibility of integrating `newsletter service` right in the app without using any 3rd party/external services.
- If Astro and Js allows such features, create `newsletter service`
- Implement such that whenever `Send Message` is hit, it is possible to add user automatically to newsletter subscription as well

**Comment by axyut** [comment]
this is partially implmented currently as there are some errors, but is completely working on the dev env so this will be closed and bugs issues will be opened
