### ISSUE TITLE
Fix CSS for Team Boxes to Adapt According to Content

### ISSUE THREAD

**Issue by BIIJESH** [b0sc/b0sc.github.io#9]
Fix the CSS for the team member boxes to ensure they automatically adapt to varying content lengths, such as different text or image sizes. This will maintain a responsive and consistent layout across devices.
![image](https://github.com/user-attachments/assets/3d548fb0-bef0-417a-a0f2-a13367261f8d)

**Comment by alexandroschanas** [comment]
Hello , you can assigned this to me if you would like
